Create direct message interface
notifirehq/notifire pull request #107
Opened 2021-11-10 15:56 UTC by scopsy

2021-11-10 17:27 UTC, davidsoderberg commented
Should direct messages have attachments?

2021-11-10 18:01 UTC, scopsy commented
@davidsoderberg I think for now we can do it without, and later we can map all providers of attachments support and release it later if needed

2021-11-13 11:26 UTC, ComBarnea commented on packages/core/src/lib/handler/direct.handler.ts
> +        '$channel_id is missing in trigger payload. To send an SMS You must specify a $phone property.'
@scopsy this needs to be updated fot direct provider error

2021-11-13 11:31 UTC, ComBarnea requested changes
See changes requested in comments

2021-11-13 14:57 UTC, merged