Feat/ Added socketPath as a prop for NovuProvider
notifirehq/notifire pull request #2998
Opened 2023-03-10 15:32 UTC by Toms-Uluks

### What change does this PR introduce?

Implements the feature described in https://github.com/novuhq/novu/issues/2994 (Support for sockets in subdirectory)

### Why was this change needed?

Closes https://github.com/novuhq/novu/issues/2994

2023-03-10 23:48 UTC, Cliftonz commented
@Toms-Uluks  Thanks for submitting this PR! 
Looks like there is a few styling errors in the docs and on the widget that the the CI found. 

Once we get those fixed, we can take a deeper look otherwise this looks great. Thanks again!

2023-03-11 21:20 UTC, LetItRock commented
hey @Toms-Uluks! 👋 
The PR looks good to me, please also verify if those new props work for the Angular and Vue packages.
Let me know after you check that and fix the CI issues, I'll review it again.

2023-03-13 07:51 UTC, Toms-Uluks commented
> @Toms-Uluks Thanks for submitting this PR! Looks like there is a few styling errors in the docs and on the widget that the the CI found.
> 
> Once we get those fixed, we can take a deeper look otherwise this looks great. Thanks again!

Oh sorry about that, should have just used a code block there.

2023-03-13 07:52 UTC, Toms-Uluks commented
> hey @Toms-Uluks! 👋 The PR looks good to me, please also verify if those new props work for the Angular and Vue packages. Let me know after you check that and fix the CI issues, I'll review it again.

Hi, yeah it works for all frameworks the same way. And should be good to go for another review now with the fix for the documentation page

2023-03-14 19:34 UTC, LetItRock commented
hey @Toms-Uluks, could you fix the linter issues in the widget? thanks! 🙌 https://github.com/novuhq/novu/actions/runs/4413366400/jobs/7745692587

2023-03-17 08:05 UTC, scopsy approved these changes

2023-03-27 16:48 UTC, scopsy commented
@Toms-Uluks seems like the tests are failing here due to broken behaviour :( Widget tests are testing the socket interactions from the client perspective

2023-05-01 15:01 UTC, Toms-Uluks commented
> @Toms-Uluks seems like the tests are failing here due to broken behaviour :( Widget tests are testing the socket interactions from the client perspective

Hi @scopsy 
Sorry for the delay on this PR, I pulled the head of the branch but I'm getting a lot of errors from DeepSource tests around parts that I haven't touched. I fixed some of them in my lates commit but I would really like to avoid touching larger ones like circular dependencies and  assigning `this` to a local variable.

2023-05-08 05:58 UTC, jainpawan21 requested changes

2023-05-08 05:58 UTC, jainpawan21 commented on docs/docs/notification-center/react/react-components.md
> +
@Toms-Uluks Please remove this extra line
lint for docs is failing due to this!

2023-08-17 09:28 UTC, scopsy commented
Hi @Toms-Uluks, I don't have the permissions to merge latest changes to here from next so I can't merge it :( 

Please let me know if you have sometime for this or should we close the PR.

2023-09-29 08:56 UTC, scopsy commented
Closing for now as stale 🙏

2023-09-29 08:56 UTC, closed without merging

2025-02-21 02:49 UTC, casyalex commented
This is useful when ws host on subdirectory...