fix: hubspot signup form issue when user is invited
notifirehq/notifire pull request #5317
Opened 2024-03-19 11:58 UTC by jainpawan21

### What change does this PR introduce?

### Why was this change needed?

### Other information (Screenshots)

2024-03-21 10:58 UTC, LetItRock requested changes
hey @jainpawan21 👋 

Please make sure to verify these cases:
1. Invited the existing user (registered by email) that is currently logged, the form should not be shown.
2. Invited the existing user (registered by email) that is not logged in, the form should not be shown.
3. Invited the existing user (registered by GH) that is currently logged, the form should not be shown.
4. Invited the existing user (registered by GH) that is not logged in, the form should not be shown.
5. Invited the new user register by email, the form should be shown.
6. Invited the new user register by GH, the form should be shown.

The case number four is failing, attaching the video.

https://github.com/novuhq/novu/assets/2607232/6b06cc7e-5afa-4d1d-85b2-eea64b8b421e

I would appreciate if you can cover the new logic with Cypress E2E tests, as far as I see we are lucking tests for the invitation logic, but it would be much appreciated if we can add them. Excluding GH flow as it's complex and requires account confirmation in E2E tests.

2024-03-21 10:58 UTC, LetItRock commented on apps/web/src/pages/auth/InvitationPage.tsx
> +      submitToken(tokensRef.current.token as string, tokensRef.current.invitationToken as string, true, false);
it's hard to understand what are there `true/false` arguments, please change it to the object, which will improve readability

2024-03-21 10:58 UTC, LetItRock commented on apps/web/src/pages/auth/components/HubspotSignupForm.tsx
> +    return () => {};
not needed

2024-03-21 10:58 UTC, LetItRock commented on apps/web/src/pages/auth/components/useAcceptInvite.ts
> +    async (token: string, invitationToken: string, refetch = false, isSignUp = true) => {
by default `isSignUp` should be `false`, we only have it set to `true` in one place - sign up form

2024-03-21 10:58 UTC, LetItRock commented on apps/web/src/pages/auth/components/SignUpForm.tsx
> -      return true;
why did we remove this `return` statement?

2024-04-07 15:36 UTC, scopsy commented
@jainpawan21 can we push to merge or close this PR? 🙏

2024-05-02 04:03 UTC, jainpawan21 commented
> @jainpawan21 can we push to merge or close this PR? 🙏

Closing this PR. I will create a new PR with requested changes.

2024-05-02 04:03 UTC, closed without merging