Simplify docker compose files
notifirehq/notifire pull request #5657
Opened 2024-05-31 17:21 UTC by Cliftonz

This PR removes old and unused docker compose files and gives more flexibility to the base docker compose file by allowing the user to select the port of the infrastructure.

2024-05-31 21:57 UTC, SokratisVidros requested changes, later dismissed

2024-05-31 21:57 UTC, SokratisVidros commented on docker/local/deployment/docker-compose.monitoring.yml
Should we merge the two docker-compose files into one? The `monitoring`, `local` suffixes are a bit misleading. We might prefer to use `docker-compose up SERVICE1 SERVICE2 ...` and target a single `docker-compose.yml`.

2024-05-31 21:57 UTC, SokratisVidros commented on docker/local/development/docker-compose.yml
> +      - "${DOCKER_LOCALSTACK_PORT}:4566"
```suggestion
      - "${DOCKER_LOCALSTACK_PORT:-4566}:4566"
```

2024-05-31 21:57 UTC, SokratisVidros commented on docker/local/development/docker-compose.yml
> +      - "${DOCKER_MONGO_PORT}:27017"
```suggestion
      - "${DOCKER_MONGO_PORT:-27017}:27017"
```

2024-05-31 21:57 UTC, SokratisVidros commented on docker/local/development/docker-compose.yml
> +      - "${DOCKER_LOCALSTACK_PORT}:4566"
I am not a 100% sure if this works but it's a nice touch to add overridable, default values.

2024-05-31 21:57 UTC, SokratisVidros commented on docker/local/development/docker-compose.yml
> +      - "${DOCKER_REDIS_SERVICE_PORT}:6379"
```suggestion
      - "${DOCKER_REDIS_SERVICE_PORT:-6379}:6379"
```

2024-06-03 11:29 UTC, Cliftonz commented on docker/local/deployment/docker-compose.monitoring.yml
I think its fine to combine and remove all of the other files. I think there was alot of bloat in here and realistically we can make the sub systems profiles.

2024-06-03 13:13 UTC, AliaksandrRyzhou approved these changes

2024-06-04 14:48 UTC, merged