Com 57 add solidjs to novujs
notifirehq/notifire pull request #5729
Opened 2024-06-13 17:11 UTC by BiswaViraj

### What changed? Why was the change needed?

- added solid js to `@novu/js`
- added `novu/js/ui` import for ui
- updated the build for solid js
### Screenshots

![image](https://github.com/novuhq/novu/assets/29251776/2b3537c7-eabb-4d2b-a8c9-0ee68b3e7452)
![image](https://github.com/novuhq/novu/assets/29251776/d7e8d7f8-a779-4cbf-8d34-2e0cc9315ee9)

<details>
<summary><strong>Expand for optional sections</strong></summary>

### Related enterprise PR

### Special notes for your reviewer

</details>

2024-06-14 16:27 UTC, LetItRock requested changes
I left you a few suggestions ;)

2024-06-14 16:27 UTC, LetItRock commented on packages/js/package.json
> +    "build:ui": "tsup --config tsup.ui.config.ts",
☑ **chore:** no need in separate build script check the suggestion below

2024-06-14 16:27 UTC, LetItRock commented on packages/js/package.json
> +      "require": "./dist/ui/index.cjs",
```suggestion
      "require": "./dist/ui/index.js",
```

2024-06-14 16:27 UTC, LetItRock commented on packages/js/package.json
> +    "./ui": {
👏 **praise:** nice! 🙌

2024-06-14 16:27 UTC, LetItRock commented on packages/js/package.json
> +    "babel-preset-solid": "^1.8.17",
is this one needed?

2024-06-14 16:27 UTC, LetItRock commented on packages/js/src/global.d.ts
> +    UI: typeof UI;
🗒 **note (non-blocking):** You didn't include it in the UMD entry file, but we should discuss whether we should... I see it might be useful but that will increase the bundle size

2024-06-14 16:27 UTC, LetItRock commented on packages/js/src/ui/App.tsx
> +const App: Component<{
```suggestion
const Inbox: Component<{
```

2024-06-14 16:27 UTC, LetItRock commented on packages/js/src/ui/index.tsx
> +export class UI {
```suggestion
export class InboxUI {
```

2024-06-14 16:27 UTC, LetItRock commented on packages/js/src/ui/index.tsx
> +      };
```suggestion
      options: NovuOptions;
```

2024-06-14 16:27 UTC, LetItRock commented on packages/js/src/ui/index.tsx
> +  }
☑ **chore:** we need to remove the node with `novu-ui` from the DOM
![Screenshot 2024-06-14 at 17 55 45](https://github.com/novuhq/novu/assets/2607232/b6c86fcf-75c3-4b58-a973-77590ac33621)

2024-06-14 16:27 UTC, LetItRock commented on packages/js/tsconfig.json
> +    "isolatedModules": true,
☑ **chore:** seems like these are not needed:
`moduleResolution` - default value is `node` when `module` is `ESNext`
`resolveJsonModule` - no need for json imports for now
`esModuleInterop and isolatedModules` - not sure about, but it works without it

2024-06-14 16:27 UTC, LetItRock commented on packages/js/tsconfig.json
> +    "noUncheckedIndexedAccess": true,
☑ **chore:** not sure if we need this, it works without

2024-06-14 16:27 UTC, LetItRock commented on packages/js/tsup.ui.config.ts
> +});
you can update the `tsup.config.ts` file with this, no need for a separate config file:

```suggestion
export default defineConfig((config) => {
  const watching = !!config.watch;

  const PARSED_DATA = preset.parsePresetOptions(PRESET_OPTIONS, watching);

  return [
    {
      ...baseModuleConfig,
      format: 'esm',
      outDir: 'dist/esm',
      tsconfig: 'tsconfig.json',
    },
    {
      ...baseModuleConfig,
      format: 'cjs',
      outDir: 'dist/cjs',
      tsconfig: 'tsconfig.cjs.json',
    },
    ...preset.generateTsupOptions(PARSED_DATA),
  ];
});
```

2024-06-14 18:47 UTC, BiswaViraj commented on packages/js/src/global.d.ts
> +    UI: typeof UI;
At first I included it but wasn't sure if it will be needed.Hence removed it afterwards as it did increased the bundle size

2024-06-17 07:22 UTC, SokratisVidros approved these changes

2024-06-17 07:23 UTC, merged