fix(js,react): inbox custom bell unread count not updating
notifirehq/notifire pull request #6362
Opened 2024-08-20 16:51 UTC by LetItRock

### What changed? Why was the change needed?
Fixed the issue with the custom bell unread count value not being updated.

Additionally in this PR, I did a few updates to the playground app:
- updated the custom notification item example
- added the case of using the custom popover component
- added the case for the custom Novu theme

### Screenshots

https://github.com/user-attachments/assets/2bc71c70-264a-44fe-8f74-c91a3c629221

https://github.com/user-attachments/assets/083525b0-8ad1-4693-8509-078564eb5f6d

2024-08-20 17:08 UTC, LetItRock commented on packages/js/src/ui/components/Notification/DefaultNotification.tsx
> +        <p class={style('notificationBody', 'nt-text-start')}>{props.notification.body}</p>
the subject and content text of the notification should be aligned to "start" which supports RTL text

2024-08-20 17:08 UTC, LetItRock commented on packages/js/src/ui/components/Notification/Notification.tsx
> +  });
this is the fix for the same case in the custom notification item, but I'll explain the reasoning in the bell component

2024-08-20 17:08 UTC, LetItRock commented on packages/js/src/ui/components/elements/Bell/Bell.tsx
> +  });
The reasoning: before we were just mounting the bell component in the `onMount` hook, but we need also to rerender it when the `totalUnreadCount` changes. The `createEffect` is called on mount and also when signals are updated and it is exactly what we need to use instead.

I thought about splitting it into `mountBell` and `updateBell` but didn't decide to do that because:
- it causes multiple re-renders on the react side because `onMount` and `createEffect` called after each other
- on the React side we don't differentiate mounts/updates as there is just one callback `renderBell`, which renders the ReactNode and updates the state

I've removed the `ExternalElementMounter` from here because the "update" phase is specific to this component and I'm not sure if we can generalize it.

2024-08-20 17:08 UTC, LetItRock commented on packages/js/src/ui/components/elements/Bell/Bell.tsx
> +  });
Also, I renamed the props so they reflect better now what that function is used for.

2024-08-20 17:08 UTC, LetItRock commented on playground/nextjs/src/components/Header.tsx
> +  { href: '/custom-popover', label: 'Custom Popover' },
two new examples in the playground

2024-08-20 17:08 UTC, LetItRock commented on playground/nextjs/src/pages/render-notification/index.tsx
> +            <div
added this example to be sure that the `renderNotification` callback is called with the new value

2024-08-20 17:21 UTC, desiprisg requested changes
Let's please reserve this PR just for the fix, and I think we should be using the mounter. Let's discuss.

2024-08-20 17:21 UTC, desiprisg commented on packages/js/src/ui/components/Inbox.tsx
> +  renderBell?: BellRenderer;
⚠️ In the JS level, this is a mount method, not a render method. I think we should keep the names as they were. This also makes more sense to be explored in a new PR, or separate discussion.

2024-08-20 17:21 UTC, desiprisg commented on packages/js/src/ui/components/elements/Bell/Bell.tsx
> +  });
I understand what you're saying. Essentially, we want the mounter to be reactive.
I think what you've done here is the same as just having `createEffect` inside the mounter, right?

2024-08-22 09:41 UTC, LetItRock commented
> Let's please reserve this PR just for the fix, and I think we should be using the mounter. Let's discuss.

I'll address all the questions/concerns on the Slack with you ;)

2024-08-22 10:41 UTC, LetItRock commented on packages/js/src/ui/components/ExternalElementRenderer.tsx
> +export const ExternalElementRenderer = ({ render, ...rest }: ExternalElementMounterProps) => {
renamed the file and component accordingly to what we agreed

2024-08-22 10:48 UTC, BiswaViraj approved these changes

2024-08-27 07:38 UTC, merged