feat(js): Fix events sharing by replacing singleton with DI
notifirehq/notifire pull request #6454
Opened 2024-09-09 07:54 UTC by BiswaViraj

### What changed? Why was the change needed?

so when we render
```
<Inbox  1/>
<Inbox  2/>
```
During the initialisation of `Inbox 1` it creates the `singletons` of inboxService and eventEmitter
Then, during the `Inbox 2` init, it re-uses the previously created `singleton` instead of creating new instances. But it does update the authorization header of the fetch requests to be of `token` from the `Inbox 2`.
So when you make requests from `Inbox 1` it uses the token of Inbox 2  and throws an error if both Inbox have different `subscriberId`.

- In this PR I replaced the `singleton` by `DI` which enables multiple independent instances of Inbox
### Screenshots

https://github.com/user-attachments/assets/51dff6e2-0e2e-45df-b706-05caee3aafef

<details>
<summary><strong>Expand for optional sections</strong></summary>

### Related enterprise PR

### Special notes for your reviewer

</details>

2024-09-09 07:56 UTC, BiswaViraj commented on packages/js/src/event-emitter/novu-event-emitter.ts
> -  private constructor() {
removed the singleton

2024-09-09 07:56 UTC, BiswaViraj commented on packages/js/src/utils/inbox-service-singleton.ts
Deleted the singleton file

2024-09-09 07:56 UTC, BiswaViraj commented on packages/js/src/novu.ts
> +    this.#emitter = new NovuEventEmitter();
initialise the services and re-use the same instances of it for other classes

2024-09-13 08:24 UTC, SokratisVidros requested changes

2024-09-13 08:24 UTC, SokratisVidros commented on packages/js/src/notifications/helpers.ts
> +  instances: {
Maybe call this `dependencies`

2024-09-13 08:24 UTC, SokratisVidros commented on packages/js/src/notifications/notification.ts
> +  constructor(notification: InboxNotification, emitter: NovuEventEmitter, inboxService: InboxService) {
This is part of the public API of the SDKs as the Notification class is pass to callbacks. Should we maybe add protected specific setters for emitter and inbox service?

2024-09-13 08:24 UTC, SokratisVidros commented on packages/js/src/novu.ts
> +      this.#inboxService,
Ditto (see Notification class)

2024-09-13 08:24 UTC, SokratisVidros commented on packages/js/src/preferences/helpers.ts
> +            {
Ditto (see Notification) class. Also here they are passed as an object whereas in the other classes they are discrete arguments in the constructor.

2024-09-13 08:31 UTC, LetItRock commented on packages/js/src/notifications/notification.ts
> +  constructor(notification: InboxNotification, emitter: NovuEventEmitter, inboxService: InboxService) {
We export just the Notification type, not a class, and callbacks receive instances, so they won't bother with the constructor.
The protected setters only work when you extend from the class, but it is still TS syntactic sugar that is not removed in JS after transpilation.

2024-09-13 10:45 UTC, SokratisVidros approved these changes

2024-09-13 13:58 UTC, merged