fix(api): remove environment id from get integration
notifirehq/notifire pull request #6493
Opened 2024-09-12 09:02 UTC by jainpawan21

### What changed? Why was the change needed?

When user is in development environment and go to production sendgrid integration, webhookurl is not showing because at API level, _environmentId is still development and integration is not found in development env. Above case can be reproduce for development integrations in production environment.
### Screenshots

<details>
<summary><strong>Expand for optional sections</strong></summary>

### Related enterprise PR

### Special notes for your reviewer

</details>

2024-09-13 08:14 UTC, SokratisVidros approved these changes

2024-09-13 08:16 UTC, SokratisVidros requested changes
Does the environment come from the Novu-Environment-Id http header? Since we have separate integrations per environment, shouldn't the environment be set regardless but not from the header?

2024-09-13 17:26 UTC, jainpawan21 commented
> Does the environment come from the Novu-Environment-Id http header? Since we have separate integrations per environment, shouldn't the environment be set regardless but not from the header?

environmentId comes with user session. Production integrations can be accessed from the development environment.

https://github.com/user-attachments/assets/9420674a-639d-48d8-a498-b766fa25bb4d

2024-10-29 06:26 UTC, jainpawan21 commented
@SokratisVidros 

Could you please review this PR again?

2024-12-13 09:35 UTC, jainpawan21 commented
@SokratisVidros 

bumping this 👆🏻

2024-12-16 10:55 UTC, scopsy approved these changes

2025-01-15 19:50 UTC, closed without merging