Com 244 hide critical workflow preferences from inbox
notifirehq/notifire pull request #6574
Opened 2024-09-25 12:29 UTC by BiswaViraj

### What changed? Why was the change needed?

### Screenshots

<details>
<summary><strong>Expand for optional sections</strong></summary>

### Related enterprise PR

### Special notes for your reviewer

</details>

2024-09-30 10:31 UTC, rifont requested changes
Looks great, just a question regarding Bridge Workflows filtering that we need to address.

2024-09-30 10:31 UTC, rifont commented on libs/application-generic/src/usecases/get-subscriber-preference/get-subscriber-preference.usecase.ts
> +        critical: command.readOnly,
The `critical` flag is always `false` for code-first Workflows created via the Bridge syncing method, so I believe this implementation will never return code-first defined Workflows when `command.readOnly=true`. Instead, Bridge defined Workflows only use the `PreferenceEntity.preferences.all.readOnly` flag to mark a Workflow as "critical".

Can you please test this and confirm?

If this is the case, we will need to fetch all Workflows (i.e. remove this additional filter on the DB layer) and perform custom filtering using JS to handle both of:
1. V1 Workflows: Workflows who have `critical: true`
2. V2 Workflows: Workflows who have `type: 'BRIDGE', combined with a `PreferenceEntity.preferences.all.readOnly: true`

2024-09-30 10:39 UTC, rifont commented on libs/application-generic/src/usecases/get-preferences/get-preferences.usecase.ts
Regarding the requested changes, if we are doing the filtering in JS, I think we should revert all changes to `get-preferences` use-case otherwise the filtering logic will become quite complex.

Futhermore, the `get-preferences` command handles logic to determine when a Preference "set" (i.e. the merged Code-First & User-defined) is `readOnly: true`. The consumer of this use-case should use that merged `readOnly` value rather than perform DB filtering operations which can prevent merging behaviour from working as intended.

2024-09-30 11:31 UTC, SokratisVidros commented on libs/application-generic/src/usecases/get-preferences/get-preferences.usecase.ts
Good catch. In this case, let's make unify the behavior without any client-specific query string option. The API

2024-09-30 15:53 UTC, rifont commented on libs/application-generic/src/usecases/get-subscriber-template-preference/get-subscriber-template-preference.command.ts
> +import { IsDefined, IsNotEmpty, IsOptional } from 'class-validator';
Can we revert the whitespace changes here and on the below file to keep the PR tidy?

2024-09-30 16:09 UTC, BiswaViraj commented on packages/js/src/ui/components/elements/Preferences/Preferences.tsx
> -              </Show>
It no more fetches the critical workflows show we don't need this UI part to indicate a workflow is critical

2024-10-01 09:25 UTC, SokratisVidros approved these changes
💯

2024-10-04 08:36 UTC, BiswaViraj commented on packages/js/src/ui/components/elements/Preferences/ChannelRow.tsx
removed UI for critical workflows

2024-10-04 08:36 UTC, BiswaViraj commented on packages/js/src/ui/components/elements/Preferences/Switch.tsx
removed data-attributes and styles related to critical workflows

2024-10-04 08:37 UTC, BiswaViraj commented on apps/api/src/app/inbox/usecases/get-preferences/get-preferences.usecase.ts
> +    const nonCriticalWorkflows = workflowPreferences.filter((preference) => preference.workflow.critical === false);
only send non-critical workflows

2024-10-04 09:10 UTC, rifont approved these changes
Awesome work! 🚅

2024-10-04 09:24 UTC, merged