refactor(api): remove $or query for hash on env
notifirehq/notifire pull request #6969
Opened 2024-11-12 15:13 UTC by scopsy

### What changed? Why was the change needed?

- Removes the legacy $or query to environments when resolving API keys
- Only use the hash key on the environment for matching

This should help with some of the ee API key transaction performance

### Screenshots

https://github.com/novuhq/packages-enterprise/pull/243
<details>
<summary><strong>Expand for optional sections</strong></summary>

### Related enterprise PR
https://github.com/novuhq/packages-enterprise/pull/243

### Special notes for your reviewer

</details>

2024-11-12 15:19 UTC, SokratisVidros requested changes
Perfect. 

Can you please also remove the caching from the following places?

With the right index, we don't need caching for this query. We must always go to Mongo.

https://github.com/novuhq/novu/blob/next/enterprise/packages/auth/src/usecases/ee.auth.service.ts#L154

https://github.com/novuhq/novu/blob/a305ec690cbdd7b89e636379cbfd36657d55a662/libs/application-generic/src/services/auth/community.auth.service.ts#L359

2024-11-12 15:19 UTC, SokratisVidros commented
@scopsy We need to add the index to the Mongoose environment schema.

2024-11-12 15:21 UTC, scopsy commented
@SokratisVidros why removing the caching for this? This will create a lot of pressure on MongoDB for information that rarely changes.

I'm very much concerned with the negative effect of removing the caching here at scale without properly monitoring it with a Feature flag

2024-11-12 15:26 UTC, SokratisVidros commented
> @SokratisVidros why removing the caching for this? This will create a lot of pressure on MongoDB for information that rarely changes.
> 
> I'm very much concerned with the negative effect of removing the caching here at scale without properly monitoring it with a Feature flag

It won't stress Mongo. Environments don't grow extremely fast; the index is super small in size, and it will always be in Mongo memory, making it work exactly like the Elastic Cache. 

It also removes the need to invalidate this cache in other places of the codebase.

2024-11-12 15:34 UTC, scopsy commented
@SokratisVidros i'm ok for trying this, but we must look on the metrics post deployment to look for any negative effects and roll back immediately.

2024-11-12 15:38 UTC, SokratisVidros commented
> @SokratisVidros i'm ok for trying this, but we must look on the metrics post deployment to look for any negative effects and roll back immediately.

Of course.

2024-11-12 16:15 UTC, SokratisVidros approved these changes
Reminder for https://github.com/novuhq/novu/blob/a305ec690cbdd7b89e636379cbfd36657d55a662/libs/application-generic/src/services/auth/community.auth.service.ts#L353

2024-11-12 17:26 UTC, rifont commented on libs/application-generic/src/services/auth/community.auth.service.ts
> -      buildAuthServiceKey({
<!-- Issues highlight specific problems with the subject under review. These problems can be user-facing or behind the scenes. It is strongly recommended to pair this comment with a suggestion. If you are not sure if a problem exists or not, consider leaving a question.  -->
⚠ **issue:** There's a few more occurrences of `buildAuthServiceKey` (including the cache invalidation for the key) that we need to remove from the code - [ref](https://github.com/search?q=repo%3Anovuhq%2Fnovu%20buildAuthServiceKey&type=code)‏

2024-11-13 08:15 UTC, merged

2024-11-13 10:18 UTC, rifont commented on libs/application-generic/src/services/auth/community.auth.service.ts
> -      buildAuthServiceKey({
hey @scopsy , I see the PR has been merged, but the above `buildAuthServiceKey` references are still present in `next`. Is there a plan to remove those? They are currently dead code and we are making a cache invalidation call that does nothing.