feat(application-generic): add SUBSCRIBER_WIDGET_JWT_EXPIRATION_TIME env variable
notifirehq/notifire pull request #7105
Opened 2024-11-21 12:29 UTC by jainpawan21

### What changed? Why was the change needed?
add `SUBSCRIBER_WIDGET_JWT_EXPIRATION_TIME` env variable to customize subscriber widget jwt expire time

ref:- [Slack conversation](https://novu.slack.com/archives/C06L08A4USH/p1732190798537669?thread_ts=1732190708.338909&cid=C06L08A4USH)

### Screenshots

<details>
<summary><strong>Expand for optional sections</strong></summary>

### Related enterprise PR

### Special notes for your reviewer

</details>

2024-11-21 12:30 UTC, scopsy approved these changes

2024-11-21 12:31 UTC, scopsy commented on apps/api/src/.example.env
> +# expressed in seconds or a string describing a time span [zeit/ms](https://github.com/zeit/ms.js).  Eg: 60, "2 days", "10h", "7d"
@jainpawan21 are comments allowed in a .env file? (don't remember if they do)

2024-11-22 00:33 UTC, jainpawan21 commented on apps/api/src/.example.env
> +# expressed in seconds or a string describing a time span [zeit/ms](https://github.com/zeit/ms.js).  Eg: 60, "2 days", "10h", "7d"
@scopsy

Yeah .env file supports comments
https://dotenvx.com/docs/env-file

2024-11-25 07:38 UTC, merrcury requested changes

2024-11-25 07:38 UTC, merrcury commented on libs/application-generic/src/services/auth/community.auth.service.ts
> +          process.env.SUBSCRIBER_WIDGET_JWT_EXPIRATION_TIME || '15 day',
Please use `env.validator.ts` in api and web

2024-11-27 13:41 UTC, scopsy approved these changes

2024-11-27 16:25 UTC, merged