fix(api): step naming
notifirehq/notifire pull request #7140
Opened 2024-11-26 23:02 UTC by djabarovgeorge

### What changed? Why was the change needed?

### Screenshots

<details>
<summary><strong>Expand for optional sections</strong></summary>

### Related enterprise PR

### Special notes for your reviewer

</details>

2024-11-27 15:40 UTC, SokratisVidros commented
@djabarovgeorge Defining the IdentifierOrInternalId type as a string doesn't add any value, so let's just drop it. Moreover, this PR is about alignment. So the naming should be the same between workflows and steps. That is `workflowIdOrInternalId` and `stepIdOrInternalId`.

2024-11-27 15:40 UTC, SokratisVidros requested changes

2024-11-27 15:40 UTC, SokratisVidros commented on apps/api/src/app/workflows-v2/usecases/build-step-data/build-step-data.command.ts
> +  workflowIdentifierOrInternalId: IdentifierOrInternalId;
```suggestion
  workflowIdOrInternalId: string;
```

2024-12-01 15:46 UTC, djabarovgeorge commented
> @djabarovgeorge Defining the IdentifierOrInternalId type as a string doesn't add any value, so let's just drop it. Moreover, this PR is about alignment. So the naming should be the same between workflows and steps. That is `workflowIdOrInternalId` and `stepIdOrInternalId`.

Thanks for the feedback! I’ve updated all the endpoints to explicitly use workflowIdOrInternalId and stepIdOrInternalId. The same changes were applied to nested use cases as well. This should make it clearer in nested cases which ID we’re working with.

2024-12-02 21:13 UTC, SokratisVidros approved these changes

2024-12-04 17:55 UTC, merged