feat(api): gracefully preview
notifirehq/notifire pull request #7190
Opened 2024-12-02 16:24 UTC by djabarovgeorge

### What changed? Why was the change needed?

### Screenshots

<details>
<summary><strong>Expand for optional sections</strong></summary>

### Related enterprise PR

### Special notes for your reviewer

</details>

2024-12-02 16:34 UTC, SokratisVidros approved these changes

2024-12-02 16:52 UTC, tatarco commented on apps/api/src/app/workflows-v2/usecases/generate-preview/generate-preview.usecase.ts
> +      Logger.error(
That won't go to sentry, and it's the wrong logger.
Need a better solution here

2024-12-02 16:53 UTC, tatarco requested changes

2024-12-02 16:53 UTC, tatarco commented on apps/api/src/app/workflows-v2/usecases/generate-preview/generate-preview.usecase.ts
> +        previewPayloadExample: {},
That is not better UX the failure

2024-12-02 18:16 UTC, djabarovgeorge commented on apps/api/src/app/workflows-v2/usecases/generate-preview/generate-preview.usecase.ts
> +        previewPayloadExample: {},
We’re working on handling edge cases to ensure the client doesn’t fail.  
One example is dealing with a stale control schema stored in the database.  
How would you approach this with a better DX?

2024-12-02 18:25 UTC, tatarco commented on apps/api/src/app/workflows-v2/usecases/generate-preview/generate-preview.usecase.ts
> +        previewPayloadExample: {},
I wrote UX, is an empty preview better than a toast error? I don't think so

Regarding the stale controls, whatever which OS under our control should not have backwards compatibility issues, the render can branch to support both v1 and v2 of a step, the errors should be rare yet we cannot stop them all, now the question is what UX is best for such issue while making sure we get alerted to fix the issue, this logger doesn't really log, it doesn't go to sentry and the response will still feel broken

2024-12-02 18:47 UTC, SokratisVidros commented on apps/api/src/app/workflows-v2/usecases/generate-preview/generate-preview.usecase.ts
> +      Logger.error(
@djabarovgeorge please also add an `import { captureException } from '@sentry/node';`

2024-12-02 18:53 UTC, SokratisVidros commented on apps/api/src/app/workflows-v2/usecases/generate-preview/generate-preview.usecase.ts
> +        previewPayloadExample: {},
Preview will only be invoked when the preview tab is selected or the mini preview is rendered - [See PR](https://github.com/novuhq/novu/pull/7186). 

The debounced preview mechanism after the introduction of autosave is redundant. Moreover, errors from the preview are not actionable by the user, as all issues will surface from the autosave. Preview, being a best-effort endpoint, will try to render as much as possible or return nothing (via a successful response).

Lastly, I agree that preview errors must be eliminated; that's why we report them to Sentry so that we can debug them, but this is an API concern. As far as the FE is concerned, the preview endpoint should always return.

2024-12-02 18:56 UTC, tatarco commented on apps/api/src/app/workflows-v2/usecases/generate-preview/generate-preview.usecase.ts
> +        previewPayloadExample: {},
as long as they are in sentry i'm ok, I'm just wandering maybe a success with some error preview syntax will be better than nothing.
I think a preview with this: 
 "error has accrued, we are working on it , here is the error id to follow up with support.
 is better than just empty.  @SokratisVidros

2024-12-03 08:12 UTC, djabarovgeorge commented on apps/api/src/app/workflows-v2/usecases/generate-preview/generate-preview.usecase.ts
> +      Logger.error(
missed this one, good catch indeed!

2024-12-03 08:41 UTC, tatarco commented on apps/api/src/app/workflows-v2/usecases/generate-preview/generate-preview.usecase.ts
> +      Logger.error(
This is the wrong logger, you should use pino instead

2024-12-03 08:42 UTC, tatarco approved these changes
please just update the correct logger , make sure the log has the sentry id as well

2024-12-03 08:49 UTC, SokratisVidros commented on apps/api/src/app/workflows-v2/usecases/generate-preview/generate-preview.usecase.ts
> +        previewPayloadExample: {},
We will get that from Sentry and act on it. We added a "No preview available" in the frontend.

2024-12-03 09:30 UTC, merged