feat(api-service): plain cards fetch user organizations
notifirehq/notifire pull request #7268
Opened 2024-12-10 22:37 UTC by jainpawan21

### What changed? Why was the change needed?
- fetch user organizations for plain cards 

### Screenshots

<details>
<summary><strong>Expand for optional sections</strong></summary>

### Related enterprise PR

### Special notes for your reviewer

</details>

2024-12-11 07:36 UTC, scopsy requested changes
💪

2024-12-11 07:36 UTC, scopsy commented on apps/api/src/app/support/dto/plain-card.dto.ts
> +export class PlainCutomer {
```suggestion
export class PlainCustomer {
```

2024-12-11 07:36 UTC, scopsy commented on apps/api/src/app/support/dto/plain-card.dto.ts
> +export class PlainCardRequestDto {
Are there any types available to export from their SDK?

2024-12-11 07:36 UTC, scopsy commented on apps/api/src/app/support/usecases/fetch-user-organizations/fetch-user-organizations.command.ts
> +export class PlainCutomer {
There seem to be some duplication in the DTO's I would suggest simplifying this a bit, or reusing if they are identical, just for simplifying our maintenance.

2024-12-11 07:36 UTC, scopsy commented on apps/api/src/app/support/usecases/fetch-user-organizations/fetch-user-organizations.command.ts
Should we consider renaming this usecases to: get-plain-cards.usecase.ts ? And then just have multiple functions for each card inside?

2024-12-11 07:36 UTC, scopsy commented on apps/api/src/app/support/support.controller.ts
> +  async getUserOrganizations(@Body() body: PlainCardRequestDto) {
How authorization happening here? We need to verify the HMAC using their signing key and enforce it.

2024-12-20 19:13 UTC, jainpawan21 commented on apps/api/src/app/support/dto/plain-card.dto.ts
> +export class PlainCardRequestDto {
No, their sdk do not export any type for card

2024-12-20 19:13 UTC, jainpawan21 commented on apps/api/src/app/support/usecases/fetch-user-organizations/fetch-user-organizations.command.ts
> +export class PlainCutomer {
reused dto in command

2024-12-20 19:18 UTC, jainpawan21 commented on apps/api/src/app/support/usecases/fetch-user-organizations/fetch-user-organizations.command.ts
renamed to plain-cards.usecase.ts

2024-12-20 19:18 UTC, jainpawan21 commented on apps/api/src/app/support/support.controller.ts
> +  async getUserOrganizations(@Body() body: PlainCardRequestDto) {
Added Plain hmac secret. linked PR https://github.com/novuhq/cloud-infra/pull/155

2024-12-22 05:20 UTC, scopsy commented on apps/api/src/app/support/support.controller.ts
> +  async getUserOrganizations(@Body() body: PlainCardRequestDto) {
@jainpawan21 but where is the logic for the validation is happening? Maybe I'm missing something 🤔

2024-12-22 05:21 UTC, scopsy commented on apps/api/src/app/support/support.controller.ts
> +  async getUserOrganizations(@Body() body: PlainCardRequestDto) {
NVM, found it 😅

2024-12-23 08:44 UTC, scopsy approved these changes

2024-12-23 08:44 UTC, scopsy commented on apps/api/src/app/support/guards/plain-cards.guard.ts
> +    const incomingSignature = request.headers['plain-request-signature'];
```suggestion
    const incomingSignature = request.headers['plain-request-signature'];
    if (!incomingSignature) throw new AuthError
```

2024-12-23 08:44 UTC, scopsy commented on apps/api/src/app/support/usecases/plain-cards.usecase.ts
> +    } else {
nitpick: Else can be removed as we exist early in the previous part

2024-12-23 14:20 UTC, scopsy approved these changes

2024-12-23 21:20 UTC, merged