feat(dashboard): variable management for all editor fields - DRAFT
notifirehq/notifire pull request #7379
Opened 2024-12-25 13:14 UTC by scopsy

### What changed? Why was the change needed?

### Screenshots

<details>
<summary><strong>Expand for optional sections</strong></summary>

### Related enterprise PR

### Special notes for your reviewer

</details>

2024-12-30 16:48 UTC, scopsy commented on apps/dashboard/public/images/code.svg
Had to add it since I need to reference it from ::after in css

2024-12-30 16:56 UTC, scopsy commented on apps/dashboard/src/utils/liquid-autocomplete.ts
> +    }
Add support for adding new payload variables

2024-12-30 16:56 UTC, scopsy commented on apps/dashboard/src/components/workflow-editor/url-input.tsx
> -                        extensions={extensions}
Extensions now live inside of the editor and not outside

2024-12-30 16:58 UTC, scopsy commented on apps/dashboard/src/components/primitives/field-editor/field-editor.tsx
> +export const FieldEditor = ({
A new component that wraps the <Editor component with the needed behaviour for content management

2024-12-30 18:38 UTC, scopsy commented on apps/dashboard/src/components/primitives/field-editor/field-editor.tsx
> +export function FieldEditor({
A new Field Editor component that uses the underlying Editor component and extends it for usage inside of content inputs

2024-12-30 19:01 UTC, scopsy commented
cc. @twentyone24

2024-12-31 08:53 UTC, SokratisVidros requested changes

2024-12-31 08:53 UTC, SokratisVidros commented on apps/dashboard/src/components/workflow-editor/steps/base/base-body.tsx
> +              <div className="w-full">
Is this div necessary since the InputField already contains a `w-full`?

2024-12-31 08:53 UTC, SokratisVidros commented on apps/dashboard/src/components/workflow-editor/steps/base/base-body.tsx
> +                  fontFamily="inherit"
This should be redundant.

2024-12-31 08:53 UTC, SokratisVidros commented on apps/dashboard/src/components/workflow-editor/steps/email/email-subject.tsx
> +              size="lg"
Why do we use the `default` size in all other control fields except the email?

2024-12-31 08:53 UTC, SokratisVidros commented on apps/dashboard/src/utils/liquid-autocomplete.ts
> +  if (word?.text.startsWith('payload.')) {
We need to add the same logic for `subscriber.data` and `digest.events[].payload`. They both allow arbitrary variables.

Subscriber.data should be supported by the API today. For digest, I need to test.

2024-12-31 08:53 UTC, SokratisVidros commented on apps/dashboard/src/utils/liquid-autocomplete.ts
> +    const existingVariables = variables.filter((v) => v.label.startsWith('payload.'));
Is this logic here to support autocompleting arbitrary variables that are not synced with the API yet? So far, the logic is that existing variables are sent from the server inside each step.

So, we need to use the ones from the server and combine them with the "draft" variables on the client side.

2024-12-31 08:53 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/field-editor.tsx
> +import { EditorView } from '@uiw/react-codemirror';
How about calling this `ControlField` or `ControlInput`? I prefer the latter as it is an input for Novu Controls. It maps better with the domain.

2024-12-31 08:53 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/field-editor.tsx
> +  const handleVariableUpdate = useVariableUpdate(
I strongly suggest merging `useVariableSelection` and `useVariableSelection` into a `useVariables` hook. The hooks are strongly connected, as the output of the first one is the input of the second. Moreover, they share the same state using common ref objects.

2024-12-31 08:53 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/field-editor.tsx
> +  const completionSource = useCompletionSource(variables, lastCompletionRef);
```suggestion
  const completionSource = useAutocomplete(variables, lastCompletionRef);
```

2024-12-31 08:53 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/field-editor.tsx
> +          <div />
Is this empty trigger necessary?

2024-12-31 08:53 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/field-editor.tsx
> +    requestAnimationFrame(() => {
`requestAnimationFrame` needs a clean-up function on unmount, similar to setTimeout. See [here](https://css-tricks.com/using-requestanimationframe-with-react-hooks/)

2024-12-31 08:53 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/field-editor.tsx
> +      const word = context.matchBefore(/\{\{([^}]*)/);
We should move all the parsing logic into the completions utility and simplify the hook.

2024-12-31 08:53 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/variable-plugin/constants.ts
> +export const VARIABLE_REGEX = /{{([^{}]+)}}/g;
Nit-picky one: Conside moving this contents to the main file. Three constants don't justify another file that adds an overhead to the live reload and building process.

2024-12-31 08:53 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/variable-popover/variable-popover.tsx
> +    const handleEscape = (e: KeyboardEvent) => {
I am surprised we have to handle escape manually. Doesn't the default ShadCN popover close on ESC?

2024-12-31 08:53 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/variable-popover/components/draggable-transformer.tsx
> +export function DraggableTransformer({
The draggable list should be a shared primitive as we will need to elsewhere.

2024-12-31 09:06 UTC, SokratisVidros commented
As I was testing this I noticed the following issues:

1. Multiple open variable autosuggestion at the same time <img width="614" alt="Screenshot 2024-12-31 at 11 00 58" src="https://github.com/user-attachments/assets/27ce05dd-0690-4091-84fd-957317c8b5bd" />
2. There are too many re-renderings on Codemirror, as we are again facing the lagging input we had in the past.
3. Handling of the Enter key is problematic. Hitting enter in single line inputs such as in-app subjects is problematic and can also break variable pills in two.

2024-12-31 12:54 UTC, LetItRock requested changes
learned a ton! 🤝 
there are a few suggestions for the improvement

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/primitives/field-editor/field-editor.tsx
> +    requestAnimationFrame(() => {
I'm not sure that we need to request an animation frame. Do we?

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/primitives/field-editor/field-editor.tsx
> +  );
These two seem to be connected and can be one hook. We pass three args from `useVariableSelection` to `useVariableUpdate`.

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/primitives/field-editor/field-editor.tsx
> +        },
this function is never called because there is no apply function on the `CompletionResult`

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/primitives/field-editor/field-editor.tsx
> +function useVariableUpdate(
please move to a separate file (imo easier to read side by side)

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/primitives/field-editor/variable-plugin/variable-theme.ts
> +    margin: '0 4px',
because of the margin:
- it's not aligned well when it is the first thing in the field, like there is a big gap on the left side
- weird cursor behaviour

here are examples:
![Screenshot 2024-12-31 at 10 25 04](https://github.com/user-attachments/assets/96219a04-284d-4da2-b69d-5cb7ceb76d28)

https://github.com/user-attachments/assets/cce7e015-ce3b-473b-a853-e02e6e17dc1b

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/primitives/field-editor/variable-plugin/variable-theme.ts
> +    borderRadius: '9999px',
10px looks enough

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/primitives/field-editor/variable-plugin/variable-theme.ts
> +  '.cm-variable-pill': {
there should be equal gap between `before` and `after` (image and dot), which is missing rn, and the items seems to close

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/primitives/field-editor/variable-plugin/variable-theme.ts
> +    transform: 'translateY(-50%)',
there is no need to render positioned absolutely, the parent is inline flex which positions `before - content - after` in a row

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/primitives/field-editor/variable-plugin/variable-theme.ts
> +  '.cm-variable-pill': {
please use class constant `VARIABLE_PILL_CLASS`

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/primitives/field-editor/variable-plugin/plugin-view.ts
> +  update(update: any) {
when the variable is picked from the autosuggestions dropdown the value does not change to pill

https://github.com/user-attachments/assets/47257c72-8145-435b-a806-5ab3fb30f26f

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/primitives/field-editor/variable-plugin/variable-pill-widget.ts
> +    (span as any)._variableClickHandler = handleClick;
can't we set it as a private field instead?

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/primitives/field-editor/variable-popover/variable-popover.tsx
> +                    <Code2 className="text-text-sub h-4 w-4" />
the icon is shrunk: 

![Screenshot 2024-12-31 at 10 26 01](https://github.com/user-attachments/assets/86ba7866-4d5c-4701-bc6a-6e88386bda68)

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/primitives/field-editor/variable-popover/variable-popover.tsx
> +                    <SelectContent
the content should be the side of the select input and look like a dropdown and not another popover

![Screenshot 2024-12-31 at 13 19 53](https://github.com/user-attachments/assets/41f28dc5-d5be-4d40-a2d7-55a9e422ef0e)

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/primitives/field-editor/variable-popover/variable-popover.tsx
> +                  >
the height should be the same of the other inputs

https://github.com/user-attachments/assets/48eb8260-06b1-4dca-9743-9454b424e1f4

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/primitives/field-editor/field-editor.tsx
> +          <VariablePopover
the popover jumps, I feel it should be aligned with the start of the variable, but not sure if that is possible

https://github.com/user-attachments/assets/07d3cc9f-83ca-41a8-a332-3a2ddf44ff9e

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/primitives/field-editor/variable-popover/variable-popover.tsx
> +export function VariablePopover({ variable, onClose, onUpdate }: VariablePopoverProps) {
![Screenshot 2024-12-31 at 10 03 20](https://github.com/user-attachments/assets/10d97e21-6cf0-402b-8912-761c9dce11ed)

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/workflow-editor/steps/in-app/in-app-subject.tsx
> +              <FieldEditor
the font size is too big

![Screenshot 2024-12-31 at 10 05 02](https://github.com/user-attachments/assets/7156d885-a529-41c6-83fe-80d267357dd1)

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/primitives/field-editor/variable-popover/variable-popover.tsx
> +export function VariablePopover({ variable, onClose, onUpdate }: VariablePopoverProps) {
when the body has validation errors they are shown in the popover fields

https://github.com/user-attachments/assets/e657edc3-3132-44c7-a65c-53e997515848

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/primitives/field-editor/variable-popover/variable-popover.tsx
> +export function VariablePopover({ variable, onClose, onUpdate }: VariablePopoverProps) {
the borders and headers of two seems to be a bit different

![Screenshot 2024-12-31 at 10 05 40](https://github.com/user-attachments/assets/bae7f0e0-64d6-4e5d-ab61-bd9e95bcdab3)

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/primitives/field-editor/variable-popover/variable-popover.tsx
> +                            </SelectItem>
the scroll does not work

https://github.com/user-attachments/assets/ae49681f-b87e-4090-b713-c205286851e8

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/primitives/field-editor/variable-popover/variable-popover.tsx
> +                    <SelectContent
on search it changes it's size

https://github.com/user-attachments/assets/c19534ce-5b20-4ae1-b811-92805b63ee02

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/primitives/field-editor/variable-popover/variable-popover.tsx
> +                    <SelectContent
when clicking outside of the modifiers it closes the variable popover 

https://github.com/user-attachments/assets/0b212216-8dd7-4ead-a8a0-9e9e47102a5b

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/primitives/field-editor/variable-popover/variable-popover.tsx
> +                    <Input value={name} onChange={(e) => handleNameChange(e.target.value)} className="h-7 text-sm" />
When there are modifiers and if the variable name gets removed all the modifiers appear in the editor.
I feel like we should only apply the changes when the popover is closed.

https://github.com/user-attachments/assets/33b2c496-ac7b-4c34-94a2-dfd25028513a

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/workflow-editor/steps/in-app/in-app-body.tsx
> +              <FieldEditor
weird focus behaviour when clicking inside/outside of the field

https://github.com/user-attachments/assets/e7c722a8-8cb5-4d72-ad64-7c2cc8e8508b

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/primitives/field-editor/field-editor.tsx
> +      autocompletion({
somehow now it's not closing the autosuggestions when clicking outside


https://github.com/user-attachments/assets/c22317cb-8b20-4e3e-9740-c02195cfebb7

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/primitives/field-editor/field-editor.tsx
> +export function FieldEditor({
react errors in the console when the popover is opened

![Screenshot 2024-12-31 at 12 21 27](https://github.com/user-attachments/assets/afc9f994-d3c5-40fa-acc1-56e72c4591cb)

2024-12-31 12:54 UTC, LetItRock commented on apps/dashboard/src/components/primitives/field-editor/variable-popover/hooks/use-variable-parser.ts
> +export function useVariableParser(variable: string) {
Can't we use liquid library for all this parsing? 
I'm not sure if that's the right thing but seems like that https://liquidjs.com/api/classes/Tokenizer.html#constructor

2025-01-02 13:45 UTC, djabarovgeorge commented on apps/dashboard/src/components/primitives/field-editor/variable-plugin/variable-pill-widget.ts
should we educate the user that the order is important? 

![image](https://github.com/user-attachments/assets/74935349-59ed-4eb7-9ce5-eba1b9892fac)

2025-01-02 21:39 UTC, scopsy commented on apps/dashboard/src/components/workflow-editor/steps/email/email-subject.tsx
> +              size="lg"
The subject in email is in bigger font size compared to the rest of the form fields we have

2025-01-03 07:42 UTC, scopsy commented on apps/dashboard/src/utils/liquid-autocomplete.ts
> +  if (word?.text.startsWith('payload.')) {
subscriber data is not supporting by API, but I will take a look at this

2025-01-03 08:54 UTC, scopsy commented on apps/dashboard/src/utils/liquid-autocomplete.ts
> +    const existingVariables = variables.filter((v) => v.label.startsWith('payload.'));
Yep it works 💪

2025-01-03 09:03 UTC, scopsy commented on apps/dashboard/src/components/primitives/field-editor/field-editor.tsx
> +          <div />
Yep, it helps with the location of the popover relative to the editor. I want to try to make it more precise by attaching to the variable not, will see if it's feasible in a reasonable amount of time

2025-01-03 09:03 UTC, scopsy commented on apps/dashboard/src/components/primitives/field-editor/field-editor.tsx
> +          <VariablePopover
It's a tricky one, i gave up on this. Will make another try with a clean head :)

2025-01-03 09:05 UTC, scopsy commented on apps/dashboard/src/components/primitives/field-editor/variable-plugin/variable-pill-widget.ts
We do provide the drag and drop to reorder,  I will consider adding a tooltip there 💪

2025-01-03 10:12 UTC, scopsy commented on apps/dashboard/src/components/primitives/field-editor/variable-popover/variable-popover.tsx
> +export function VariablePopover({ variable, onClose, onUpdate }: VariablePopoverProps) {
Regarding the error state visible on all field it happens because of the InputField, I will refactor this to the new stateless inputs in the Design System PR

2025-01-03 10:13 UTC, scopsy commented on apps/dashboard/src/components/primitives/field-editor/variable-popover/variable-popover.tsx
> +                    <Input value={name} onChange={(e) => handleNameChange(e.target.value)} className="h-7 text-sm" />
I think I will leave it for now as it's seem to be not a critical scenario,

2025-01-03 10:18 UTC, scopsy commented on apps/dashboard/src/components/workflow-editor/steps/in-app/in-app-body.tsx
> +              <FieldEditor
Will be handleed by the aligned inputs PR

2025-01-03 10:19 UTC, scopsy commented on apps/dashboard/src/components/primitives/field-editor/variable-plugin/constants.ts
> +export const VARIABLE_REGEX = /{{([^{}]+)}}/g;
Agree, But they are used across different files, and I didn't want to end up in a weird cyclical dependencies scenario.

2025-01-03 10:29 UTC, scopsy commented on apps/dashboard/src/components/primitives/field-editor/variable-plugin/plugin-view.ts
> +  update(update: any) {
Unfortuently couldn't find on how we can achieve this, spent quite a lot of time on this. Will leave it as-is for now

2025-01-03 10:55 UTC, scopsy commented on apps/dashboard/src/components/primitives/field-editor/variable-popover/variable-popover.tsx
> +    const handleEscape = (e: KeyboardEvent) => {
There is a small delay when the parent sheet is closing, which annoyed me, but it's not significant tho. Will remove it.

2025-01-03 11:06 UTC, scopsy commented on apps/dashboard/src/components/primitives/field-editor/variable-popover/variable-popover.tsx
> +                    <SelectContent
Refactored this to use a command component

2025-01-03 11:15 UTC, scopsy commented
@SokratisVidros I've improved some useMemo usecases, but other than that I couldn't notice any significant degradation compared to staging or prod. Let me know if you have some specific scenarios we might want to optimize.

2025-01-10 22:23 UTC, SokratisVidros requested changes

2025-01-10 22:23 UTC, SokratisVidros commented on apps/api/src/app/workflows-v2/shared/map-step-type-to-result.mapper.ts
> +            payload:
Was this a bug on digest? Why additional properties are required?

2025-01-10 22:23 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/field-editor.tsx
> +type CompletionRange = {
Nitpicky one; it isn't very intuitive to define a type as null. The CompletionRange type variable, can be of that type or null.

2025-01-10 22:23 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/field-editor.tsx
> +  singleLine?: boolean;
Nit picky DX, most of the time the FieldEditor is single line, so multiline is the exception. That is, we should revert the prop to `multiline` that defaults to false.

2025-01-10 22:23 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/field-editor.tsx
> +import { autocompletion } from '@codemirror/autocomplete';
If I am not mistaken, I wrote this comment again, but the field terminology is foreign to the Novu domain. This is about step controls, so the naming of such a pivotal component should reflect the domain. That is, we can call it ControlEditor or ControlInput

2025-01-10 22:23 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/field-editor.tsx
> +  const variablePlugin = useMemo(
Since everything else is an extension...

```suggestion
  const variableExtension = useMemo(
```

2025-01-10 22:23 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/hooks/use-variables.ts
> +type SelectedVariable = {
Ditto about null.

2025-01-10 22:23 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/hooks/use-variables.ts
> +  const [selectedVariable, setSelectedVariable] = useState<SelectedVariable>(null);
```suggestion
  const [selectedVariable, setSelectedVariable] = useState<SelectedVariable | null>(null);
```

2025-01-10 22:23 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/hooks/use-variables.ts
> +        const hasLiquidSyntax = newValue.match(/^\{\{.*\}\}$/);
The regex also matches variables with multiple brackets such as `{{{{foo}}}}` or `{{{{{{{foo}}}`. We should either consider it invalid or squash multiple {{{{ and }}} to two on each side.

2025-01-10 22:23 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/variable-plugin/index.ts
> +export function createVariablePlugin({ viewRef, lastCompletionRef, onSelect }: PluginState) {
```suggestion
export function createVariableExtension({ viewRef, lastCompletionRef, onSelect }: PluginState) {
```

2025-01-10 22:23 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/variable-plugin/index.ts
> +export * from './constants';
Nit-picky one, I'd just move constants here to remove an extra file.

2025-01-10 22:23 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/variable-plugin/utils.ts
> +    fullVariableName,
```suggestion
    expression,
```

2025-01-10 22:23 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/variable-plugin/utils.ts
> +    variableName,
```suggestion
    name,
```

2025-01-10 22:23 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/variable-plugin/utils.ts
> +    hasModifiers,
Let's return all the liquid filters in an array instead of a boolean. I am sure we will use them later. Also since this is about Liquid Filters, we should rename the variable.

2025-01-10 22:23 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/variable-plugin/utils.ts
> +export function handleVariableBackspace(view: EditorView, pos: number, content: string): boolean {
:bulp If I get it right, this ensures the pill is treated as a single character during keyboard interactions. Code mirror uses content-editable divs. So, to create pills that behave as a single character inside a content-editable div, there is a technique to nest non-content-editable spans.

See [here](https://jsbin.com/mohuyokena/edit?html,output). Since we fully control the rendering process with the view plugin, maybe it provides a non-JS solution to the problem.

2025-01-10 22:23 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/variable-plugin/variable-pill-widget.ts
> +      other.fullVariableName === this.fullVariableName &&
The full expression of the variable along with the start and end position should be enough for the comparison.

2025-01-10 22:23 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/variable-plugin/variable-theme.ts
> +    fontSize: '12px',
Do we have font and typography-related CSS root variables to use as we did with colors?

2025-01-10 22:23 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/variable-plugin/variable-theme.ts
> +    maskImage: `url("/images/code.svg")`,
If not mistaken we can do `content: url("/images/code.svg");`. Is the maskImage required for anything else? If not, let's simplify it.

2025-01-10 22:23 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/variable-popover/components/draggable-transformer.tsx
> +export const DraggableTransformer = forwardRef<HTMLDivElement, DraggableTransformerProps>(
This component deserves being a top level primitive called Sortable, used from the variable popover, to drag and sort Liquid filters.

2025-01-10 22:23 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/variable-popover/components/transformer-item.tsx
> +export function TransformerItem({ transformer }: TransformerItemProps) {
As per Liquid.js jargon and [Novu Lexicon](https://www.notion.so/novuhq/Product-Terminology-Lexicon-d6ef923953744bc1b967ba8f297dee7f?pvs=4#15bd03ad838f8070a697c74fa7f8efa7) these are Liquid Filters, not transformers.

I strongly advice aligning the terminology across the board to easy the future reader.

2025-01-10 22:23 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/variable-popover/components/transformer-list.tsx
> +      <AnimatePresence mode="popLayout">
Ditto about the sortable primitive.

2025-01-10 22:23 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/variable-popover/hooks/use-transformer-manager.ts
> +export function useTransformerManager({ initialTransformers, onUpdate }: UseTransformerManagerProps) {
It feels that these hooks belong to the sortable component and they need to be generalized to control the sortable state.

2025-01-10 22:23 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/variable-popover/variable-popover.tsx
> +  const handleRawLiquidChange = useCallback((value: string) => {
Shouldn't this code be part of the useVariableParser logic? Ideally, we should centralize all the logic about variable parsing and formatting to a single file, so that if we need to modify or expand the syntax, we do it in one place. Currently the logic is scattered across files.

2025-01-10 22:23 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/variable-popover/variable-popover.tsx
> +                        <span>Add a modifier...</span>
I suggest we call them filters in the UI as well. Since we will talk about Novu using Liquid.js we need to stick to the terminology of the template engine.

2025-01-10 22:23 UTC, SokratisVidros commented on apps/dashboard/src/components/primitives/field-editor/variable-popover/variable-popover.tsx
> +            <TransformerList
```suggestion
            <FilterSelector
```

2025-01-12 08:18 UTC, scopsy commented on apps/api/src/app/workflows-v2/shared/map-step-type-to-result.mapper.ts
> +            payload:
Yes, it was not allowed to add new variables when used with the auto complete flow. cc @djabarovgeorge

2025-01-12 08:30 UTC, scopsy commented on apps/dashboard/src/components/primitives/field-editor/field-editor.tsx
> +import { autocompletion } from '@codemirror/autocomplete';
I aggree! Done.

2025-01-12 09:15 UTC, scopsy commented on apps/dashboard/src/components/primitives/field-editor/variable-plugin/variable-theme.ts
> +    fontSize: '12px',
nope, currently all of the definitions are managed inside of the tailwind config file only. I will take a look at this at later stage as part of the new tailwind version upgrade, where they are moving away from the tailwind config file into a CSS variable native approach.

2025-01-12 09:16 UTC, scopsy commented on apps/dashboard/src/components/primitives/field-editor/variable-popover/components/draggable-transformer.tsx
> +export const DraggableTransformer = forwardRef<HTMLDivElement, DraggableTransformerProps>(
I have left it out intentionally for the time being, I'm not sure entirely where and how this is going to be used in other places, and would prefer to extract it when needed as it's not a primitive on our design system yet.

2025-01-13 16:57 UTC, SokratisVidros approved these changes

2025-01-14 10:14 UTC, merged